version: "3.8"
services:

  # Nextcloud main backend

  nextcloud:
    image: nextcloud:28.0.2-fpm
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    volumes:
      - nextcloud_data:/var/www/html:z
      - ./php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
      - REDIS_HOST
      - OVERWRITEPROTOCOL
      - OVERWRITEHOST
      - TRUSTED_PROXIES
      - APACHE_DISABLE_REWRITE_IP
      - PHP_FPM_MAX_CHILDREN=256 # Adjust the number based on your server resources
    restart: unless-stopped
    depends_on:
      - caddy
      - db
      - redis

  # Cron job
  
  cron:
    image: nextcloud:28.0.2-fpm
    container_name: nextcloud-cron
    networks:
      - nextcloud_network
    volumes:
      - nextcloud_data:/var/www/html:z
    entrypoint: /cron.sh
    restart: unless-stopped
    depends_on:
      - db
      - redis

  # database 

  db:
    image: mariadb:11.2.3
    container_name: mariadb-database
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - nextcloud_network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    restart: unless-stopped

  # web server

  web:
    image: nginx:1.25.4-alpine3.18
    container_name: nextcloud-web
    networks:
      - nextcloud_network
    links:
      - nextcloud
    labels:
      - "caddy.reverse_proxy=true"
      - "caddy.header.Strict-Transport-Security=max-age=15552000;"
      - "caddy.rewrite_0=/.well-known/carddav /remote.php/dav"
      - "caddy.rewrite_1=/.well-known/caldav /remote.php/dav"
      - "caddy.rewrite_2=/.well-known/webfinger /index.php/.well-known/webfinger"
      - "caddy.rewrite_3=/.well-known/nodeinfo /index.php/.well-known/nodeinfo"
    volumes:
      - nextcloud_data:/var/www/html:z,ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
  
  # Redis cache

  redis:
    image: redis:7.2.4-alpine
    container_name: redis-dbcache
    networks:
      - nextcloud_network
    restart: unless-stopped
  
  # Reverse proxy and SSL certificate handler

  caddy:
    image: caddy:2.7.6-alpine
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - nextcloud_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped
  
networks:
  nextcloud_network:
    external: true

volumes:
  caddy_data: 
    external: true
  db_data:
    external: true
  nextcloud_data:
    external: true