servers = [
  { :hostname => "ex2-00", :ip => "192.168.133.50" },
  # { :hostname => "ex2-01", :ip => "192.168.133.51" },
]

Vagrant.configure("2") do |config|
  # fedora39 caused some issues with the k8s installation
  config.vm.box = "fedora/38-cloud-base"
  config.vm.box_version = "38.20230413.1"

  config.vm.provider :libvirt do |lv|
    lv.qemu_use_session = false
    lv.memory = 2048
    lv.cpus = 2
  end

  servers.each do |conf|
    config.vm.define conf[:hostname] do |node|
      node.vm.hostname = conf[:hostname]
      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.network :private_network,
                      :libvirt__network_name => 'ex2-net'

      node.vm.provision :shell, 
                        :path => './scripts/0_bash_common_provisioning.sh',
                        :args => [ conf[:ip] ]
      node.vm.provision :shell,
                        :path => './scripts/1_install_k8s.sh'
      node.vm.provision :shell,
                        :path => './scripts/1bis_kubectl_nonroot.sh'

    end
  end
end
