servers = [
  { :hostname => "ex2", :ip => "192.168.132.50" },
  # { :hostname => "ex2-01", :ip => "192.168.132.51" },
]

scripts = [
  './scripts/00_bash_common_provisioning.sh',
  './scripts/01_install_k8s.sh',
  './scripts/02_other_conveniences.sh',
]

Vagrant.configure("2") do |config|
  # fedora39 caused some issues with the k8s installation
  config.vm.box = "fedora/38-cloud-base"
  config.vm.box_version = "38.20230413.1"

  config.vm.provider :libvirt do |lv|
    lv.qemu_use_session = false
    lv.memory = 2048
    lv.cpus = 2
  end

  servers.each do |conf|
    config.vm.define conf[:hostname] do |node|
      node.vm.hostname = conf[:hostname]
      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.network :private_network,
                      :libvirt__network_name => 'ex2-net'

      scripts.each do |script|
        node.vm.provision :shell,
                          :path => script,
                          :args => [conf[:ip]] # needed to the 00_bash_common_provisioning
      end
    end
  end
end

