apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: "" # local-path
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /home/vagrant/pvs/nextcloud
  # hostPath:
  #   path: /home/vagrant/pvs/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ex2-00

  # local --> node-specific configuration for a pod 
  # hostPath --> share the same volume among pods on the same node