apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  # namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # local-path  # Empty string indicates dynamic provisioning without a specific storage class
